### ISSUE TITLE
Relicense?

### ISSUE THREAD

**Issue by jayvdb** [d-e-s-o/serve_variant#4]
Hi, I was going to use this at https://github.com/Electron100/butane/pull/236

However because this crate is GPL, it is incompatible with the license of that project.
I see many of the crates in https://crates.io/crates/serde_variant/reverse_dependencies are also not GPL, and therefore shouldnt be using this crate either.

Would you consider switching to a more permissive license, such as MIT or Apache-2.0 ?

**Comment by d-e-s-o** [comment]
Hi, yes, I can relicense under a more permissive license. Will get it done by the weekend.
